name: Sync com PR

on:
  push:
  #repository_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: actions
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: fga-eps-mds/2024.1-UnB-TV-Admin
          ref: develop

      - name: Checkout the fork
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: victorleaoo/2024.1-UnB-TV-Admin
          ref: develop

      - name: Merge upstream changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/fga-eps-mds/2024.1-UnB-TV-Admin.git
          git fetch upstream
          git merge upstream/develop
          git push origin develop
